- id: cinder_nfs
  type: puppet
  role: [primary-controller, controller, cinder]
  required_for: [deploy_end]
  requires: [openstack-cinder]
  parameters:
    puppet_manifest: cinder_nfs.pp 
    puppet_modules: /etc/puppet/modules
    timeout: 600
