- id: cinder_nfs
  type: puppet
  groups: [primary-controller, controller]
  role: [primary-controller, controller]
  required_for: [deploy_end]
  requires: [openstack-cinder]
  parameters:
    puppet_manifest: cinder_nfs.pp 
    puppet_modules: /etc/puppet/modules/
    timeout: 600
