attributes:
 server_ip:
    value: ''
    label: 'NFS server ip'
    desciption: 'NFS server ip'
    weight: 25
    type: "text"
 share_name:
    value: ''
    label: 'NFS server share path'
    desciption: 'NFS server share'
    weight: 20
    type: "text"
desciption: ""
